### ISSUE TITLE
iMap/Routes on mobile browser issues

### ISSUE THREAD

**Issue by evantrillium** [trilliumtransit/kern-theme#1]
This client is experiencing route map and route list visibility issues on their mobile device (see below)
![C99C088B-9B8F-4E4E-841B-3F78128E2DDC](https://user-images.githubusercontent.com/31700284/54144704-80de3d00-43e9-11e9-90c5-4933f4a0e398.png)

It also looks like iMap generally isn't working well for this site, even when appearing correctly. Are there any recommendations/improvements that we can make at this time?

**Comment by thomastrillium** [comment]
Site needs a mobile overhaul--but there's an easy fix here.

It's not iMap that's messed up on mobile, it's just the routes and schedules page.

The front-page map isn't clickable on mobile, and there's no route list. That means user has to go to routes and schedules page. That page is iMap app only, sized the wrong height for the page.

System map isn't really necessary on mobile. I think best short term fix is just replace the routes and schedules page with a list of links to route pages, and call it good. But alternate idea is to fix whatever is making iMap size itself wrong on mobile devices if that's trivial.

**Comment by livemixlove** [comment]
@thomastrillium  Is this something you would like me to work on?

**Comment by thomastrillium** [comment]
@NomeQ does have a lot on her plate so if you're available to take a look that would be great!

**Comment by livemixlove** [comment]
ok!

**Comment by evantrillium** [comment]
@livemixlove have you had a chance to poke at this yet?

**Comment by livemixlove** [comment]
The map works without issues on my android, and it also works on browserstack.com running iphone+safari on iPhone 8 and 6.  @evantrillium  Do you know what browser/device the original screenshot it from?

**Comment by livemixlove** [comment]
Works on iphone XS too.

**Comment by livemixlove** [comment]
@evantrillium  do you know the specific url from that screenshot?

**Comment by evantrillium** [comment]
@livemixlove let me reach out to Norma and see if I can get you more details

**Comment by livemixlove** [comment]
Oh, nevermind.  I found the problem.  I've seen this before.  It makes the embed super tall.  I'll have to remember what we did last time to fix this or if it was every fixed on other sites.

**Comment by livemixlove** [comment]
Individual route pages are fine, it's the routes and schedules page where there's the issue.

**Comment by livemixlove** [comment]
@evantrillium  no need to reach out to client again, as I was looking at the wrong pages.  I can see it now on the iphone simulator.

**Comment by livemixlove** [comment]
Possible fix: https://stackoverflow.com/questions/34320046/iframe-height-issues-on-ios-mobile-safari

**Comment by livemixlove** [comment]
@NomeQ  do you remember fixing an iframe height issue on another website?  I do vaguely, but I forget which site it was.  Also, is Kern setup with the autodeploy setup?

**Comment by livemixlove** [comment]
Another possible fix: https://gist.github.com/Mao8a/5963675

**Comment by livemixlove** [comment]
I might try to fix the iframe issues, but if that's too finicky, then I'll just do " I think best short term fix is just replace the routes and schedules page with a list of links to route pages, and call it good." which I think is actually a better user experience.

**Comment by NomeQ** [comment]
If I recall correctly, the fix I used in the past was to change the embed
styling on the theme page, rather than to change the interactive map. I
think we do need to change that at some point, since it's come up on
several sites, but I never was able to put together a universal fix.

**Comment by livemixlove** [comment]
Ok, now narrow screen devices will see a list of route buttons instead of map on the routes & schedules page.  Also, the ftp is synched to the github production branch via deployHQ.
