### ISSUE TITLE
Illustrated Map Updates

### ISSUE THREAD

**Issue by NomeQ** [trilliumtransit/kern-theme#4]
Route 130 now extends to Santa Clarita, and the long name is now Santa Clarita - Bakersfield. Attached is the rough image of the change.
![2D4B3B1B-787F-4A7E-96A0-C77BDABF29B5](https://user-images.githubusercontent.com/9342771/58357124-79e29a80-7e2e-11e9-8435-2b97fa1f5db2.png)

**Comment by thomastrillium** [comment]
please let's just use this map :)

**Comment by livemixlove** [comment]
Ok I've pushed the new map: ec69b09a215c0948e378b35559bcab7f6a0d126f

**Comment by livemixlove** [comment]
@NomeQ deployhq failed to push https://trillium.deployhq.com/projects/kern-transit/deployments/fbdcdc01-5302-48cc-af6b-61900049e2d4

> Checking access to repository
> 
> Checking start and end revisions are valid
> 
> Checking connection to server Development
> 
> We couldn't login to your server Development. Host key has changed. The most likely cause of this is that you or your ISP have recently changed your server. Alternatively, it could be indicative of someone trying to hijack the connection to your server. You can reset the public key for your server from the Edit Server Properties page.

**Comment by livemixlove** [comment]
Interesting. I get the same "host key changed" error when trying to connect via SFTP.

**Comment by livemixlove** [comment]
Solution on my mac was to
1) check if host entry for kern exists
`cat ~/.ssh/known_hosts | grep wpengine`
2) remove that entry.
...sftp works again.

**Comment by livemixlove** [comment]
Used this to fix deployHQ: https://www.deployhq.com/support/common-deployment-errors/server-host-key-changed

**Comment by NomeQ** [comment]
Oh yeah, WP Engine changed the host key/server for all our sites a few
weeks back, so all the sites need them reset. It's almost always the reason
a deployment fails. Thanks, Paul!

**Comment by livemixlove** [comment]
Oh I just realized I didn't update the route name in the map... one sec.

**Comment by livemixlove** [comment]
@NomeQ  there's another step which is to change the route URL to the new Santa Clarita route name.  This will require the map layer names to change at the same time.
